### ISSUE TITLE
Specifying the icon word e.g 'twitter' does not work in Firefox Mac

### ISSUE THREAD

**Issue by scottsweb** [kudakurage/LigatureSymbols#12]
I am experiencing a strange issue where the icons are not being rendered when specified as a word but they are working we specified as unicode. This is only happening in Firefox. For example:

```
.icon { content: 'twitter'; } // fails
.icon { content: '\E12f'; } // works
```

Any ideas why Firefox may be struggling with this?

**Comment by kudakurage** [comment]
Hi, scottsweb. Thanks the report!!
I know it dosen't work sometimes in Firefox, Chrome and Safari. But I don't know the cause :-(
If you clear the cache, it may work. For example, you will rename the font files.
