### ISSUE TITLE
soundcloud?

### ISSUE THREAD

**Issue by mcfiredrill** [kudakurage/LigatureSymbols#13]
A soundcloud logo would be awesome!

http://www.soundcloud.com

![](https://w.soundcloud.com/icon/assets/images/orange_white_32-94fc761.png)

**Comment by kudakurage** [comment]
Thans your message and request!!
Updated to ver.2.1 and add new symbols (ubunte, soundcloud, etc...)

**Comment by mcfiredrill** [comment]
Awesome !!!
:thumbsup: :thumbsup: :thumbsup: :star: :exclamation:
