### ISSUE TITLE
Calendar is spelled wrong

### ISSUE THREAD

**Issue by markbranly** [kudakurage/LigatureSymbols#5]
In both **calendar** and **dailycalendar**, it is currently spelled _calender_.

Great work, BTW! Outside of HTML/CSS awesomeness, it really speeds up design time in Photoshop too. Cheers.

**Comment by kudakurage** [comment]
Oh, sorry! Thanks good advice. Immediately revise it!

**Comment by kudakurage** [comment]
Fixed spell miss 'calendar' and updated font file to ver.2.09!!
