### ISSUE TITLE
Yelp

### ISSUE THREAD

**Issue by stephenway** [kudakurage/LigatureSymbols#6]
Would be really nice to get a Yelp icon.

**Comment by kudakurage** [comment]
Thans your message and request!!
Updated to ver.2.1 and add new symbols (ubunte, soundcloud, etc...)

**Comment by stephenway** [comment]
I'm confused, doesn't look like Yelp was added?

**Comment by kudakurage** [comment]
Sorry....
It didn't include "Yelp" by my mistake.
Updated to ver.2.11 and add new symbol (yelp) !

**Comment by stephenway** [comment]
Sweet thank you!
