### ISSUE TITLE
Add unicode hex values for CSS pseudo element

### ISSUE THREAD

**Issue by dangayle** [kudakurage/LigatureSymbols#9]
You can't use html entities in a css pseudo element, because it inserts the ampersand and everything :

```
a:before { content: '&#xe139;'; }
```

In order to get it to work, you have to use the unicode hex values, which are stupid hard to figure out:

```
a:before { content: '\E139'; }
```

I had to use this [unicode code converter](http://rishida.net/tools/conversion/) to get the proper codepoints, but it would be super awesome if you provided them to begin with along with the html entities.

Great font, BTW!

**Comment by kudakurage** [comment]
Thanks for comment. It seems as you say.
I'll fix it!!!

**Comment by zhouqicf** [comment]
thx.
